// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDlJiXzLn5deYFhIxc5x5tdabkXD6-Fow',
    appId: '1:724709524099:web:3c5c335479df22690e51b6',
    messagingSenderId: '724709524099',
    projectId: 'fir-bookapp-4bc6c',
    authDomain: 'fir-bookapp-4bc6c.firebaseapp.com',
    storageBucket: 'fir-bookapp-4bc6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHxi6PUz9M-1sS0eE1tuMF3kMDONSJXC8',
    appId: '1:724709524099:android:cc8abc9ee24a05850e51b6',
    messagingSenderId: '724709524099',
    projectId: 'fir-bookapp-4bc6c',
    storageBucket: 'fir-bookapp-4bc6c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDlJiXzLn5deYFhIxc5x5tdabkXD6-Fow',
    appId: '1:724709524099:web:f850df64b9ac031b0e51b6',
    messagingSenderId: '724709524099',
    projectId: 'fir-bookapp-4bc6c',
    authDomain: 'fir-bookapp-4bc6c.firebaseapp.com',
    storageBucket: 'fir-bookapp-4bc6c.appspot.com',
  );
}
